### ISSUE TITLE
CUDA files fail very noisily

### ISSUE THREAD

**Issue by gridley** [deoplete-plugins/deoplete-clang#92]
## Problems summary

Hi, has anyone tried using this with CUDA? I have loved using this plugin lately, but on CUDA files, it seems to get very angry. It would be nice to just have it not autocomplete, but instead, it seems that the python3 interface to clang raises some error about not being able to parse the translation unit. This confuses me, because I thought that clang 6 was cool with CUDA.

I would love to try to fix this rather than just complain, but have no clue how this plugin works.

## Expected

Not putting a wall of red text in front of me while  writing CUDA code. :smile: 

## Environment Information

 - OS: ubuntu 18.04
 - Neovim version: 0.5.0-dev

## Provide a minimal init.vim with less than 50 lines and not plugin manager (Required!)

```vim
set smartindent
filetype plugin on
filetype indent on
set ruler
set hlsearch
set incsearch
set magic
syntax on
set encoding=utf8
set expandtab
set smarttab
set tabstop=2
set shiftwidth=2

" autocompletion
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-6.0/lib/libclang.so.1'
let g:deoplete#sources#clang#clang_header = '/usr/lib/llvm-6.0/lib/clang/6.0.0/include'

" Open files to same line they were last closed on.
autocmd BufReadPost * if @% !~# '\.git[\/\\]COMMIT_EDITMSG$' && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif

```

or, try use it [tests/deoplete-clang.vim](../tests/deoplete-clang.vim)

## The reproduce ways from neovim starting (Required!)

 1. Open the below file in nvim (with a .cu extension on it), then try to edit some text.

```cuda
#include <iostream>
using namespace std;

__constant__ unsigned asdf;

__global__ void printSecretMessage()
{
  printf("Waddup %i\n", asdf);
}

int main()
{
  unsigned secret;
  cout << "Please input secret unsigned:" << endl;
  cin >> secret;
  cout << "Secret is " << secret << endl;
  cudaMemcpyToSymbol(asdf, (void*)&secret, sizeof(unsigned), 0, cudaMemcpyHostToDevice);
  printSecretMessage<<<1,32>>>();
  cudaDeviceSynchronize();
}
```
## Log

[log_py3_rplugin.txt](https://github.com/deoplete-plugins/deoplete-clang/files/3707286/log_py3_rplugin.txt)

## Screen shot (if possible)

![vim-fail](https://user-images.githubusercontent.com/18088906/66481331-aeb65d80-ea6e-11e9-8a7d-ad280c3907a1.png)

## Upload the log file
 - `NVIM_PYTHON_LOG_FILE`
 - `$HOME`/.nvimlog

**Comment by Shougo** [comment]
Sorry.  Current deoplete-clang is old.  And not maintained well.
I recommend for you to use deoplete-clangx or LSP instead.
